Start using the token file
shopmonkeyus/eds-server pull request #169
Opened 2024-08-05 15:33 UTC by potofpie

- Read the token file if we dont have a parameter
- Create datadir correctly if we dont pass a parameter
-  Add the serverId in the POST to create the session

2024-08-05 16:14 UTC, jhaynie requested changes

2024-08-05 16:14 UTC, jhaynie commented on cmd/enroll.go
> +	enrollCmd.Flags().String("data-dir", filepath.Join(cwd+"/datadir"), "the data directory for storing logs and other data")
```suggestion
	enrollCmd.Flags().String("data-dir", filepath.Join(cwd, "datadir"), "the data directory for storing logs and other data")
```

2024-08-05 16:14 UTC, jhaynie commented on cmd/root.go
> +type EnrollTokenData struct {
we should use viper instead. viper is built by the same people that built cobra and it makes it trivial to create configs that also bind to command line arguments and environment variables.

https://github.com/spf13/viper

also we should probably choose something a bit more user friendly in the config format like TOML

2024-08-12 19:32 UTC, robindiddams requested changes
Enroll fails if theres no config file yet, should probably check the config file differently in that case. Also theres some weirdness with the viper config, [heres an example](https://gist.github.com/robindiddams/bb7db28ba9efc1b9517e18aaf10349f6) setup that lets you sorta configure it globally. Also that flag

`go mod tidy` to cleanup that mod file

2024-08-12 19:32 UTC, robindiddams commented on cmd/enroll.go
> +	"github.com/BurntSushi/toml"
yoooo BurntSushi! that takes me back!

2024-08-12 19:32 UTC, robindiddams commented on cmd/enroll.go
> +	Token    string `json:"token" toml:"server_id`
```suggestion
	Token    string `json:"token" toml:"token`
```
ya gotta get that golang vscode plugin, `go vet ./...` will catch this for you

2024-08-12 19:32 UTC, robindiddams commented on cmd/server.go
> +	cobra.OnInitialize(initConfig)
this should go in root.go

2024-08-12 19:32 UTC, robindiddams commented on cmd/fork.go
> +	forkCmd.Flags().String("data-dir", filepath.Join(cwd, "dataDir"), "the data directory for storing state, logs, and other data")
lets just make data-dir a persistent flag on the rootCmd

2024-08-12 19:32 UTC, robindiddams commented on cmd/root.go
> +	viper.AddConfigPath("./dataDir")
you cant use `/` in path names this breaks on windows. also you're hard coding this here but allowing it to be passed in elswhere which will conflict

2024-08-12 19:32 UTC, robindiddams commented on cmd/server.go
> +			apikey = viper.GetString("token")
should just bind the viper flag `token` to the flag `api-key`

2024-08-12 20:46 UTC, robindiddams requested changes

2024-08-12 20:46 UTC, robindiddams commented on cmd/root.go
> +	}
still need 

```go
	if err := viper.ReadInConfig(); err != nil {
   // 🤷‍♀️
	}
```

2024-08-12 20:46 UTC, robindiddams commented on cmd/root.go
> +	rootCmd.PersistentFlags().String("config", filepath.Join(cwd, "dataDir/config.toml"), "the data directory for storing state, logs, and other data")
N/O S/L/A/S/H/E/S

```suggestion
	rootCmd.PersistentFlags().String("config", filepath.Join(cwd, "dataDir", "config.toml"), "the data directory for storing state, logs, and other data")
```

2024-08-12 20:53 UTC, potofpie commented on cmd/root.go
> +	rootCmd.PersistentFlags().String("config", filepath.Join(cwd, "dataDir/config.toml"), "the data directory for storing state, logs, and other data")
lol true!

2024-08-13 13:55 UTC, robindiddams requested changes
this isnt right, the full path is supposed to be the default. We should just have one flag for the data dir and `initConfig` should just append `config.toml` to the end of it.

2024-08-13 13:55 UTC, robindiddams commented on cmd/root.go
> +	}
extra error check?

2024-08-13 13:55 UTC, robindiddams commented on cmd/enroll.go
> +			log.Fatal(err)
`logger` not `log` dont use the log package

2024-08-13 14:59 UTC, robindiddams approved these changes

2024-08-13 14:59 UTC, merged